from Caixeiro import funcoes

N_CIDADES = 15
COORDENADAS = funcoes.geraCoordenadas(N_CIDADES)
CIDADE_PARTIDA = 3
TAM_POPULACAO = 500

#AG
N_CROSSOVER = int(TAM_POPULACAO * 0.5)
N_MUTACAO = int(TAM_POPULACAO * 0.25)
MAX_GERACOES = 100
MUDANCA_MENOR = 5
